kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nodeplugin-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: csi-nodeplugin-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-nodeplugin-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io  
