kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nodeplugin{{- if .Values.multiInstanceMode }}-{{ .Release.Namespace }}{{- end }}
subjects:
  - kind: ServiceAccount
    name: csi-nodeplugin
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-nodeplugin{{- if .Values.multiInstanceMode }}-{{ .Release.Namespace }}{{- end }}
  apiGroup: rbac.authorization.k8s.io  
