kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vlz-csi-controller-binding{{- if .Values.multiInstanceMode }}-{{ .Release.Namespace }}{{- end }}
subjects:
  - kind: ServiceAccount
    name: vlz-csi-controller-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: vlz-csi-controller-role{{- if .Values.multiInstanceMode }}-{{ .Release.Namespace }}{{- end }}
  apiGroup: rbac.authorization.k8s.io
