kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role{{- if .Values.multiInstanceMode }}-{{ .Release.Namespace }}{{- end }}
subjects:
  - kind: ServiceAccount
    name: csi-attacher
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: external-attacher-runner{{- if .Values.multiInstanceMode }}-{{ .Release.Namespace }}{{- end }}
  apiGroup: rbac.authorization.k8s.io
