apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: vlz{{- if .Values.multiInstanceMode }}-{{ .Release.Namespace }}{{- end }}
spec:
  attachRequired: true
  podInfoOnMount: true
  fsGroupPolicy: {{ .Values.vlzCsiDriver.fsGroupPolicy }}