apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: vlz-{{ .Release.Name }}-{{ .Release.Namespace }}
spec:
  attachRequired: true
  podInfoOnMount: true
  fsGroupPolicy: {{ .Values.vlzCsiDriver.fsGroupPolicy }}