---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.vlzDriverNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher
  namespace: {{ .Values.vlzDriverNamespace }}
