kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: vlz-csi-controller
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "vlz-csi-controller"
  replicas: 1
  selector:
    matchLabels:
      app: vlz-csi-controller
  template:
    metadata:
      labels:
        app: vlz-csi-controller
        deploymentRevisionId: "{{ .Release.Revision }}" # this here updates and forces refresh
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: vlz-csi-controller-sa
      containers:
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:{{ .Values.sidecars.snapshotter.tag }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=90s"
            - "--retry-interval-start=10s"
            - "--retry-interval-max=40m"
            - "--extra-create-metadata"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: csi-snapshot-controller
          image: registry.k8s.io/sig-storage/snapshot-controller:{{ .Values.sidecars.snapshotController.tag }}
          args:
            - "--v=5"
          imagePullPolicy: IfNotPresent

        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:{{ .Values.sidecars.provisioner.tag }}
          args:
            - "--csi-address=$(ADDRESS)"
            - "--extra-create-metadata"
            - "--feature-gates=Topology=true"
            - "--timeout=320s"
            - "--retry-interval-start=10s"
            - "--retry-interval-max=40m"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:{{ .Values.sidecars.attacher.tag }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=200s"
            - "--retry-interval-start=10s"
            - "--retry-interval-max=40m"
            - "--worker-threads={{ .Values.sidecars.attacher.workers }}"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:{{ .Values.sidecars.resizer.tag }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=200s"
            - "--retry-interval-start=10s"
            - "--retry-interval-max=40m"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: vlz-snapshotrollback-controller
          image: "{{ .Values.vlzSnapshotRollbackController.repository }}:{{ .Values.vlzSnapshotRollbackController.tag }}"
          imagePullPolicy: "Always"
          args:
            - "--volumezendpoint=$(VOLUMEZ_ENDPOINT)"
            - "--volumezEndpointBasePath=$(VOLUMEZ_ENDPOINT_BASE_PATH)"
            - "--volumezauthtoken=$(VOLUMEZ_AUTH_TOKEN)"
          env:
            - name: VOLUMEZ_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: vlz-config
                  key: VOLUMEZ_ENDPOINT
            - name: VOLUMEZ_ENDPOINT_BASE_PATH
              valueFrom:
                configMapKeyRef:
                  name: vlz-config
                  key: VOLUMEZ_ENDPOINT_BASE_PATH
            - name: VOLUMEZ_AUTH_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: vlz-config
                  key: VOLUMEZ_AUTH_TOKEN

        - name: vlz
          image: "{{ .Values.vlzCsiDriver.repository }}:{{ .Values.vlzCsiDriver.tag }}"
          imagePullPolicy: "Always"
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--volumez-endpoint=$(VOLUMEZ_ENDPOINT)"
            - "--volumez-endpoint-base-path=$(VOLUMEZ_ENDPOINT_BASE_PATH)"
            - "--volumez-auth-token=$(VOLUMEZ_AUTH_TOKEN)"
            - "--run-connector=$(RUN_CONNECTOR)"
            - "--connector-force-install=$(CONNECTOR_FORCE_INSTALL)"
            - "--connector-download-repository-base-url=$(CONNECTOR_DOWNLOAD_REPOSITORY_BASE_URL)"
            - "--connector-api-domain=$(CONNECTOR_API_DOMAIN)"
            - "--env-id=$(ENV_ID)"
            - "--driver-suffix=$(DRIVER_NAME_SUFFIX)"
            - "--v=$(VERBOSE_LEVEL)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: RUN_CONNECTOR
              value: "false"
          envFrom:
            - configMapRef:
                name: vlz-config
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
      volumes:
        - name: socket-dir
          emptyDir:
{{- if .Values.vlzCsiController.tolerations }}
      tolerations:
{{ toYaml .Values.vlzCsiController.tolerations | indent 8 }}
{{- end -}}
{{- if .Values.vlzCsiController.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.vlzCsiController.nodeSelector | indent 8 }}
{{- end -}}
