kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-attacher-vlzplugin
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "csi-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: csi-attacher-vlzplugin
  template:
    metadata:
      labels:
        app: csi-attacher-vlzplugin
        webhook: vlz-admission-webhook
        deploymentRevisionId: "{{ .Release.Revision }}" # this here updates and forces refresh
    spec:
      serviceAccountName: csi-attacher
      containers:
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:{{ .Values.k8s.snapshotterTag }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=90s"
            - "--retry-interval-start=10s"
            - "--retry-interval-max=40m"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: csi-snapshot-controller
          image: registry.k8s.io/sig-storage/snapshot-controller:{{ .Values.k8s.snapshotControllerTag }}
          args:
            - "--v=5"
          imagePullPolicy: IfNotPresent

        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:{{ .Values.k8s.provisionerTag }}
          args:
            - "--csi-address=$(ADDRESS)"
            - "--extra-create-metadata"
            - "--feature-gates=Topology=true"
            - "--timeout=320s"
            - "--retry-interval-start=10s"
            - "--retry-interval-max=40m"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:{{ .Values.k8s.attacherTag }}
          args:
            - "--v=7"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=400s"
            - "--retry-interval-start=5s"
            - "--retry-interval-max=15m"
            - "--worker-threads=100"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:{{ .Values.k8s.resizerTag }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=200s"
            - "--retry-interval-start=10s"
            - "--retry-interval-max=40m"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: vlz-snapshotrollback-controller
          image: "{{ .Values.vlzSnapshotRollbackController.repository }}:{{ .Values.vlzSnapshotRollbackController.tag }}"
          imagePullPolicy: "Always"
          args:
            - "--volumezendpoint=$(VOLUMEZ_ENDPOINT)"
            - "--volumezEndpointBasePath=$(VOLUMEZ_ENDPOINT_BASE_PATH)"
            - "--volumezauthtoken=$(VOLUMEZ_AUTH_TOKEN)"
          env:
            - name: VOLUMEZ_ENDPOINT
              value: "{{ .Values.vlzEndpoint.apiUrl }}"
            - name: VOLUMEZ_ENDPOINT_BASE_PATH
              value: "{{ .Values.vlzEndpoint.basePath }}"
            - name: VOLUMEZ_AUTH_TOKEN
              value: "{{ .Values.vlzAuthToken }}"

        - name: vlz
          image: "{{ .Values.vlzCsiDriver.repository }}:{{ .Values.vlzCsiDriver.tag }}"
          imagePullPolicy: "Always"
          args :
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--volumez-endpoint=$(VOLUMEZ_ENDPOINT)"
            - "--volumez-endpoint-base-path=$(VOLUMEZ_ENDPOINT_BASE_PATH)"
            - "--volumez-auth-token=$(VOLUMEZ_AUTH_TOKEN)"            
            - "--run-connector=$(RUN_CONNECTOR)"
            - "--connector-force-install=$(CONNECTOR_FORCE_INSTALL)"
            - "--connector-download-repository-base-url=$(CONNECTOR_DOWNLOAD_REPOSITORY_BASE_URL)"
            - "--connector-api-domain=$(CONNECTOR_API_DOMAIN)"
            - "--env-id=$(ENV_ID)"
            - "--driver-suffix=$(DRIVER_NAME_SUFFIX)"
            - "--v=$(VERBOSE_LEVEL)"

          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: VOLUMEZ_ENDPOINT
              value: "{{ .Values.vlzEndpoint.apiUrl }}"
            - name: VOLUMEZ_ENDPOINT_BASE_PATH
              value: "{{ .Values.vlzEndpoint.basePath }}"
            - name: VOLUMEZ_AUTH_TOKEN
              value: "{{ .Values.vlzAuthToken }}"
            - name: RUN_CONNECTOR
              value: "false"
            - name: CONNECTOR_FORCE_INSTALL
              value: "{{ .Values.vlzConnector.forceInstall }}"
            - name: CONNECTOR_DOWNLOAD_REPOSITORY_BASE_URL
              value: "{{ .Values.vlzConnector.repoUrl }}"
            - name: ENV_ID
              value: "{{ .Values.envId }}"
            - name: DRIVER_NAME_SUFFIX
              value: "{{- if .Values.multiInstanceMode }}{{ .Release.Namespace }}{{- end }}"
            - name: VERBOSE_LEVEL
              value: "{{ .Values.verboseLevel }}"

          volumeMounts:
            - name: socket-dir
              mountPath: /plugin

        - image: "{{ .Values.vlzAdmissionWebhook.repository }}:{{ .Values.vlzAdmissionWebhook.tag }}"
          imagePullPolicy: "Always"
          name: vlz-admission-webhook
          env:
            - name: TLS
              value: "true"
            - name: LOG_LEVEL
              value: "trace"
            - name: LOG_JSON
              value: "false"
          volumeMounts:
            - name: tls
              mountPath: "/etc/admission-webhook/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: vlz-admission-webhook-tls
        - name: socket-dir
          emptyDir:
{{- if .Values.csiAttacherVlzplugin.tolerations }}
      tolerations:
{{ toYaml .Values.csiAttacherVlzplugin.tolerations | indent 8 }}
{{- end -}}
{{- if .Values.csiAttacherVlzplugin.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.csiAttacherVlzplugin.nodeSelector | indent 8 }}
{{- end -}}
