apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "vlz-admission-webhook.volumez.com"
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/vlz-admission-webhook-serving-cert
webhooks:
  - name: "vlz-admission-webhook.volumez.com"
    rules:
      - apiGroups: ["vlzcontroller.k8s.io"]
        apiVersions: ["*"]
        operations: ["UPDATE"]
        resources: ["snapshotrollbacks"]
        scope: "*"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: vlz-admission-webhook
        path: /validate-snapshotrollback
        port: 443
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
