apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: vlz-admission-webhook-{{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/sync-wave": "2"
  name: vlz-admission-webhook-serving-cert-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - vlz-admission-webhook.{{ .Release.Namespace }}.svc
    - vlz-admission-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: vlz-admission-webhook-selfsigned-issuer-{{ .Release.Name }}
  secretName: vlz-admission-webhook-tls-{{ .Release.Name }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: vlz-admission-webhook-{{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/sync-wave": "2"
  name: vlz-admission-webhook-selfsigned-issuer-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
