apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: vlz-admission-webhook
  name: vlz-admission-webhook-serving-cert
  namespace: {{ .Values.vlzDriverNamespace }}
spec:
  dnsNames:
    - vlz-admission-webhook.{{ .Values.vlzDriverNamespace }}.svc
    - vlz-admission-webhook.{{ .Values.vlzDriverNamespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: vlz-admission-webhook-selfsigned-issuer
  secretName: vlz-admission-webhook-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: vlz-admission-webhook
  name: vlz-admission-webhook-selfsigned-issuer
  namespace: {{ .Values.vlzDriverNamespace }}
spec:
  selfSigned: {}