---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vlz-admission-webhook
  name: vlz-admission-webhook
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 30100
  selector:
    webhook: vlz-admission-webhook
