apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: vlz-admission-webhook
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
  name: vlz-admission-webhook-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - vlz-admission-webhook.{{ .Release.Namespace }}.svc
    - vlz-admission-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: vlz-admission-webhook-selfsigned-issuer
  secretName: vlz-admission-webhook-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: vlz-admission-webhook
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
  name: vlz-admission-webhook-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}