name: CSI Regression Pipeline

on: 
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - development
  
jobs:
  aks_regression:
    name: AKS Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AKS Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USERNAME }}
          token: ${{ secrets.JENKINS_TOKEN2 }}
          job: Regression_V3
          parameters: >
            Test_Plan=QA-5282,
            Private_SB=${{ github.head_ref || github.ref_name }},
            AWS_EC2_OS=aks_latest,
            AWS_APP_OS=aks_latest,
            Config_File=aks_fast_regression_default.json,
            Manifest_Branch=master,
            pipeline_automation_branch=master,
            is_ms_mode=True,
            AWS_EC2_VNL=True,
            AWS_APP_VNL=True

  eks_regression: 
    name: EKS Regression Tests
    runs-on: ubuntu-latest
    needs: aks_regression
    steps:
      - name: Trigger EKS Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USERNAME }}
          token: ${{ secrets.JENKINS_TOKEN2 }}
          job: Regression_V3
          parameters: >
            Test_Plan=QA-5282,
            Private_SB=${{ github.head_ref || github.ref_name }},
            AWS_EC2_OS=eks_latest,
            AWS_APP_OS=eks_latest,
            Config_File=eks_fast_regression_default.json,
            Manifest_Branch=master,
            pipeline_automation_branch=master,
            is_ms_mode=True,  
            AWS_EC2_VNL=True,
            AWS_APP_VNL=True 
