name: Release Charts Dev

on:
  pull_request:
    types:
      [opened, reopened, edited, synchronize]
    branches:
      - development

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n 1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        with:
          skip_existing: true   
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
